### PR TITLE
Support for building non-KSU variant

### PR DESCRIPTION
**Pull request by hoang1007**
Add guard for KernelSU hooks to support build without KernelSU

### CODE REVIEW

**Comment by EndCredits** [comment]
Thanks for your contribution, now let's improve this patch.

**Comment by EndCredits** [comment]
@hoang1007 How do you think?

**Comment by hoang1007** [comment]
Great, I think it is ready to be merged!

**Comment by EndCredits** [comment]
Ok, thanks for your contribution!

**Pull request merged**
